// <auto-generated />
namespace LNP.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Products : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Products));
        
        string IMigrationMetadata.Id
        {
            get { return "202505182223045_Products"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
